### PR TITLE
Feature/dummy labview

### PR DESCRIPTION
**Pull request by cbernet**
* web server can now be deployed in the stack as a docker container
* script that can inject dummy labview data
* migration to pyproject.toml 
* improved documentation

### CODE REVIEW

**Comment by cbernet** [comment]
@ArnabPurohit can you please review this PR whenever possible ? I'm waiting for your review to merge. Don't hesitate to ask questions as PR comments

**Comment by cbernet** [comment]
@ArnabPurohit still on it ?

**Comment by ArnabPurohit** [comment]
> @ArnabPurohit still on it ?

Yes

**Comment by ArnabPurohit** [comment]
I have reviewed the PR and tested it in my private area. It works as intended. I have no other questions than above.

**Pull request merged**
